#! /usr/bin/env node
/*
	child_process 子进程方式
	
	使用方式:
	1.修改文件权限: chmod 755 helloWithChildProcess
	2.运行
	./helloWithChildProcess kings
	=> hello kings

*/
var name = process.argv[2];
var exec = require('child_process').exec;

var child = exec('echo hello '+ name, function(err, stdout, stderr) {
	if (err) throw err;
	console.log(stdout)
})