var colors = require('colors');

console.log('hello'.green)
console.log('i like cake and pies'.underline.red)
console.log('inverse the color'.inverse)
console.log('OMG Rainbows!'.rainbow)
console.log('OMG Rainbows!'.zebra)
console.log('OMG Rainbows!'.america)
console.log('OMG Rainbows!'.random)
console.log('Run the trap'.trap)
console.log('Hello World'.bgRed)
console.log('Hello World'.bgGreen)
console.log('Hello World'.bgYellow)
console.log('Hello World'.bgBlue)
console.log('Hello World'.bgMagenta)
console.log('Hello World'.bgCyan)
console.log('Hello World'.bgWhite.green)
console.log('Hello World'.bgBlack.white)